- name: "bond"
  assets:
    - "IMA"
#    - "IMA-S"
    - "IMA-B"
#    - "IMA-B 5"
#    - "IMA-B 5+"
    - "IMA-B 5 P2"
    - "IRF-M"
#    - "IRF-M 1"
#    - "IRF-M 1+"
    - "IRF-M P2"
  benchmark: "CDI"

- name: "equity"
  assets:
    - "IBrX 50"
    - "Ibovespa"
    - "IBrX"
    - "IBrA"
#    - "IDIV"
  benchmark: "CDI"

- name: "multi-asset"
  assets:
    - "Giant Zarathustra + Sigma"
    - "Giant Darius + Sigma"
    - "Pandhora Essencial"
  benchmark: "CDI"

- name: "index"
  assets:
    - "IBrX"
    - "IFIX"
    - "IMA-B 5 P2"
  benchmark: "CDI"
  weights: "naive risk contribution"

- name: "index-zarathustra-sigma"
  assets:
    - "IBrX"
    - "IFIX"
    - "IMA-B 5 P2"
    - "Giant Zarathustra + Sigma"
  benchmark: "CDI"
  weights: "naive risk contribution"

- name: "index-darius-sigma"
  assets:
    - "IBrX"
    - "IFIX"
    - "IMA-B 5 P2"
    - "Giant Darius + Sigma"
  benchmark: "CDI"
  weights: "naive risk contribution"
