Row
--------------------------------------------------------------------------------

### Metrics
```{r}
analysis %>% 
    magrittr::extract2("metric_table") %>% 
    percentage_columns() %>%
    knitr::kable()
```


Row
--------------------------------------------------------------------------------

### Price
```{r}
analysis %>% 
    magrittr::extract2("price_plot") %>% 
    plotly::ggplotly()
```

### Relative price
```{r}
analysis %>% 
    magrittr::extract2("relative_price_plot") %>% 
    plotly::ggplotly()
```


Row {.tabset .tabset-fade}
--------------------------------------------------------------------------------

### Rolling year return
```{r}
analysis %>% 
    magrittr::extract2("rolling_year_return_plot") %>% 
    plotly::ggplotly()
```

### Year quantiles
```{r}
analysis %>% 
    magrittr::extract2("rolling_year_return_table") %>%
    percentage_columns() %>%
    knitr::kable()
```

### Month quantiles
```{r}
analysis %>% 
    magrittr::extract2("rolling_month_return_table") %>%
    percentage_columns() %>%
    knitr::kable()
```

### Week quantiles
```{r}
analysis %>% 
    magrittr::extract2("rolling_week_return_table") %>% 
    percentage_columns() %>%
    knitr::kable()
```

### Drawdown
```{r}
analysis %>% 
    magrittr::extract2("drawdown_plot") %>% 
    plotly::ggplotly()
```


Row {.tabset .tabset-fade}
--------------------------------------------------------------------------------

### Relative Rolling year return
```{r}
analysis %>% 
    magrittr::extract2("relative_rolling_year_return_plot") %>% 
    plotly::ggplotly()
```

### Relative Year quantiles
```{r}
analysis %>% 
    magrittr::extract2("relative_rolling_year_return_table") %>%
    percentage_columns() %>%
    knitr::kable()
```

### Relative Month quantiles
```{r}
analysis %>% 
    magrittr::extract2("relative_rolling_month_return_table") %>%
    percentage_columns() %>%
    knitr::kable()
```

### Relative Week quantiles
```{r}
analysis %>% 
    magrittr::extract2("relative_rolling_week_return_table") %>% 
    percentage_columns() %>%
    knitr::kable()
```

### Relative Drawdown
```{r}
analysis %>% 
    magrittr::extract2("relative_drawdown_plot") %>% 
    plotly::ggplotly()
```


Row
--------------------------------------------------------------------------------

### Correlations
```{r}
analysis %>% 
    magrittr::extract2("correlation_table") %>% 
    percentage_columns() %>%
    knitr::kable()
```

### Clustering
```{r}
analysis %>% 
    magrittr::extract2("dendogram_plot") %>% 
    plotly::ggplotly()
```
