name: Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  RENV_PATHS_ROOT: ~/.local/share/renv

jobs:
  pipeline:
    name: Run pipeline
    runs-on: ubuntu-latest
    container: rocker/verse
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Cache renv packages
        uses: actions/cache@v2
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: ${{ runner.os }}-renv-

      - name: Install dependencies
        run: |
          sudo apt-get upgrade -y
          make dependencies

      - name: Run pipeline
        run: |
          mkdir -p output/dashboard/
          make pipeline
        env:
          QUANDL_API_KEY: ${{ secrets.QUANDL_API_KEY }}

#      - name: Setup tmate session
#        uses: mxschmitt/action-tmate@v3

      - name: Commit generated dashboards
        run: |
          git checkout origin/gh-pages
          rsync -a output/dashboard/ dashboard/
          git add dashboard/
          git commit -m "Auto commit: add generated dashboards"
          git push origin gh-pages
