name: Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  RENV_PATHS_ROOT: ~/.local/share/renv

jobs:
  pipeline:
    name: Run pipeline
    runs-on: ubuntu-latest
    container: rocker/verse
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Cache renv packages
        uses: actions/cache@v2
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: ${{ runner.os }}-renv-

      - name: Install dependencies
        run: |
          sudo apt-get upgrade -y
          make dependencies

      - name: Run pipeline
        run: |
          make pipeline
        env:
          QUANDL_API_KEY: ${{ secrets.QUANDL_API_KEY }}

      - name: Install rsync
        run: |
          apt-get update && apt-get install -y rsync

      - name: Deploy GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: gh-pages
          folder: github-pages
